.Dd July 30, 2024
.Dt README 7
.Os "Libreboot"
.Sh NAME
.Pp
.Nm lbman
.Nd man pages for Libreboot
.Sh DESCRIPTION
.Pp
The
.Nm
repository hosts experimental manual pages for Libreboot.
.Sh BUILDING HTML PAGES
.Pp
.Bd -literal -offset indent
\&./configure
make
.Ed
.Sh SEE ALSO
.Bl -item
.It
.Lk https://libreboot.org Libreboot's official website
.El
.\" vim: tw=72
